// <auto-generated />
using System;
using CoachingSchoolLeassons.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoachingSchoolLeassons.API.Migrations
{
    [DbContext(typeof(CoachingSchoolDbContext))]
    [Migration("20240310174104_Initialize Migration")]
    partial class InitializeMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoachingSchoolLeassons.API.Models.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DayAndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CoachingSchoolLeassons.API.Models.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee"),
                            Name = "Student"
                        },
                        new
                        {
                            Id = new Guid("7742d5ad-776d-4b67-b32b-dc7c57a6a97c"),
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("7744c786-47c5-439d-8c82-4b4b1109f9a9"),
                            Name = "SuperUser"
                        });
                });

            modelBuilder.Entity("CoachingSchoolLeassons.API.Models.Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77a99d53-5a5f-4d5d-a56e-a8da6dfdff66"),
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = new Guid("75c1905d-00ad-401a-94e1-700350d61e63"),
                            Name = "Greek"
                        },
                        new
                        {
                            Id = new Guid("10c1905d-00ad-401a-94e1-700350d61e63"),
                            Name = "Mandarin"
                        },
                        new
                        {
                            Id = new Guid("20c1905d-00ad-401a-94e1-700350d61e63"),
                            Name = "English"
                        });
                });

            modelBuilder.Entity("CoachingSchoolLeassons.API.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5dccc28e-c1d9-48f4-ab15-57ca98375b60"),
                            FirstName = "Giannis",
                            LastName = "Kamperakis",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("6c8c4096-7734-499a-a3cf-bc8b5e6aac0f"),
                            FirstName = "Kalliroi",
                            LastName = "Eustratiou",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("0ec91ce7-48a1-4b57-8cba-59e6a679b975"),
                            FirstName = "Maria",
                            LastName = "Aslanidou",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("b06cdf54-0efe-4e1b-9c8c-95ba57674eec"),
                            FirstName = "Giorgos",
                            LastName = "Papadopoulos",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("93fee0bd-b3b8-4623-b070-957e93f15cd0"),
                            FirstName = "Ilias",
                            LastName = "Kazanias",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("d2d7c9fc-9e3b-464a-80ff-0bb3b099f4b2"),
                            FirstName = "Stavros",
                            LastName = "Iliiadakis",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("da0f197b-5e6f-475c-bb86-a4b46904e76b"),
                            FirstName = "Loukas",
                            LastName = "Iliadakis",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("03c833f5-b1c7-4b4c-b601-0ff89b737090"),
                            FirstName = "Giorgos",
                            LastName = "Armadopoulos",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("f6df939d-20dc-4d20-b85b-7cc98412b1a4"),
                            FirstName = "Giannis",
                            LastName = "Loukiadis",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("e4b163c2-a785-4525-b18a-b07a66de6aef"),
                            FirstName = "Aristotelis",
                            LastName = "Sofianos",
                            RoleId = new Guid("c39618f0-9cd5-4d68-88e9-5b2ffe924cee")
                        },
                        new
                        {
                            Id = new Guid("3d28154c-a358-4c56-bef1-61bad294be3c"),
                            FirstName = "Mike",
                            LastName = "van Oheilly",
                            RoleId = new Guid("7742d5ad-776d-4b67-b32b-dc7c57a6a97c")
                        },
                        new
                        {
                            Id = new Guid("f47bc91d-a949-412b-9c28-0ee682dad6c1"),
                            FirstName = "July",
                            LastName = "Kennedy",
                            RoleId = new Guid("7742d5ad-776d-4b67-b32b-dc7c57a6a97c")
                        },
                        new
                        {
                            Id = new Guid("05042e39-cc2d-4759-9e52-2d970c4ee955"),
                            FirstName = "Thomas",
                            LastName = "Preachon",
                            RoleId = new Guid("7742d5ad-776d-4b67-b32b-dc7c57a6a97c")
                        },
                        new
                        {
                            Id = new Guid("0be4c1c5-76ca-4a5e-95b8-13a7578182a2"),
                            FirstName = "Pete",
                            LastName = "Luca",
                            RoleId = new Guid("7742d5ad-776d-4b67-b32b-dc7c57a6a97c")
                        },
                        new
                        {
                            Id = new Guid("4844084f-a7c4-49bb-adfb-bd7d31b7c828"),
                            FirstName = "John",
                            LastName = "Admin",
                            RoleId = new Guid("7744c786-47c5-439d-8c82-4b4b1109f9a9")
                        });
                });

            modelBuilder.Entity("CoachingSchoolLeassons.API.Models.Domain.UserSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserSubjects");
                });

            modelBuilder.Entity("CoachingSchoolLeassons.API.Models.Domain.User", b =>
                {
                    b.HasOne("CoachingSchoolLeassons.API.Models.Domain.Group", null)
                        .WithMany("Users")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("CoachingSchoolLeassons.API.Models.Domain.Group", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
